server:
  port: 8200

spring:
  profiles:
    active: dev
  application:
    name: product-service
  cloud:
    nacos:
      discovery:
        server-addr: ${unique-mall.nacos.host}:${unique-mall.nacos.port}
      username: ${unique-mall.nacos.username}
      password: ${unique-mall.nacos.password}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${unique-mall.datasource.host}:${unique-mall.datasource.port}/${unique-mall.datasource.database}
    username: ${unique-mall.datasource.username}
    password: ${unique-mall.datasource.password}
  data:
    redis:
      host: ${unique-mall.redis.host}
      port: ${unique-mall.redis.port}
      password: ${unique-mall.redis.password}
      database: ${unique-mall.redis.database}

unique-mall:
  snowflake:
    datacenter-id: ${unique-mall.snowflake.datacenter-id}
    worker-id: ${unique-mall.snowflake.worker-id}

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
